[package]
name = "handshake"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = {version = "2.0.11"}
async-trait = {version = "0.1.85"}
tokio = {version = "1.0.0",features = ["full"]}
futures = {version = "0.3.31"}